version: '3'
services:
  server:
    build:
      context: server/
      dockerfile: Dockerfile
    volumes:
      - ./server/src:/server/src
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
  client:
    build:
      context: client/
      dockerfile: Dockerfile
    volumes:
      - ./client/src:/client/src
    depends_on:
      - server
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
